# Dependencies
markdown:         kramdown
highlighter:      rouge

# Permalinks
permalink:        pretty

# Setup
title:            Emanuel Huber
tagline:          "R-package RGPR"
description:      'A R package to read, write, analyse and visualise ground-penetrating radar (GPR) data.'
url:              https://emanuelhuber.github.io/
baseurl:          

#author:
#  name:           'Mark Otto'
#  url:            https://twitter.com/mdo

paginate:         5

# Custom vars
version:          0.2

#github:
#  repo:          https://github.com/poole/hyde



collections:          
  projects:
    output: true
